### ISSUE TITLE
GraphQLSchemaProvider.copyReadonly ignores coderegistry (which breaks interface types)

### ISSUE THREAD

**Issue by pvgoddijn** [graphql-java-kickstart/graphql-java-servlet#147]
i;m trying to build a code defined schema icm with `AbstractGraphQLHttpServlet` and am running into the problem that if i use 

```
invocationInputFactory = GraphQLInvocationInputFactory.newBuilder(mycode.getSchema()).build();
```
to supply that factory to the servlet it works in simple cases but breaks when i introduce interface types

This seems to originate from the `DefaultGraphQLSchemaProvider` which makes a readonly copy of the schema like so:
```
    static GraphQLSchema copyReadOnly(GraphQLSchema schema) {
        return GraphQLSchema.newSchema().query(schema.getQueryType()).build(schema.getAdditionalTypes());
    }
```
this build a new schema with a empy code registry and thus cant find my type resolvers for the interface type.
I cant really find out what the readonly copy is intended for but changing it to:

```
    static GraphQLSchema copyReadOnly(GraphQLSchema schema) {
         return GraphQLSchema.newSchema()
                         .query(schema.getQueryType())
		 	 .additionalTypes(schema.getAdditionalTypes())
			.codeRegistry(schema.getCodeRegistry())
			.build();
}
```
fixes it for me.

i have however no idea wether or not this was intentional

**Comment by oliemansm** [comment]
I'm looking at that method in `GraphQLSchemaProvider` and `GraphQLSchema`, but can't find that `codeRegistry` you mention here?

**Comment by pvgoddijn** [comment]
The problem lies in  `DefaultGraphQLSchemaProvider`

the builder method: 
```
    public static Builder newBuilder(GraphQLSchema schema) {
        return new Builder(new DefaultGraphQLSchemaProvider(schema));
    }
```
invokes the constructor of `DefaultGraphQLSchemaProvider`  which makes a readonly copy
```
GraphQLSchemaProvider.copyReadOnly(schema)
```
During this copy process it validates the new schema.
That validation fails because the typeresolvers arent found (because they are not copied)

```
tomcat_1                 | graphql.AssertException: There must be a type resolver for interface Project
tomcat_1                 | 	at graphql.Assert.assertNotNull(Assert.java:15)
tomcat_1                 | 	at graphql.schema.GraphQLCodeRegistry.getTypeResolverForInterface(GraphQLCodeRegistry.java:117)
tomcat_1                 | 	at graphql.schema.GraphQLCodeRegistry.access$700(GraphQLCodeRegistry.java:28)
tomcat_1                 | 	at graphql.schema.GraphQLCodeRegistry$Builder.getTypeResolver(GraphQLCodeRegistry.java:208)
tomcat_1                 | 	at graphql.schema.CodeRegistryVisitor.visitGraphQLInterfaceType(CodeRegistryVisitor.java:40)
tomcat_1                 | 	at graphql.schema.GraphQLInterfaceType.accept(GraphQLInterfaceType.java:153)
tomcat_1                 | 	at graphql.schema.TypeTraverser$TraverserDelegateVisitor.enter(TypeTraverser.java:71)
tomcat_1                 | 	at graphql.util.Traverser.traverse(Traverser.java:144)
tomcat_1                 | 	at graphql.schema.TypeTraverser.doTraverse(TypeTraverser.java:58)
tomcat_1                 | 	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:50)
tomcat_1                 | 	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:38)
tomcat_1                 | 	at graphql.schema.SchemaUtil.extractCodeFromTypes(SchemaUtil.java:112)
tomcat_1                 | 	at graphql.schema.GraphQLSchema$Builder.lambda$build$1(GraphQLSchema.java:413)
tomcat_1                 | 	at graphql.schema.GraphQLCodeRegistry.transform(GraphQLCodeRegistry.java:139)
tomcat_1                 | 	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:413)
tomcat_1                 | 	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:384)
tomcat_1                 | 	at graphql.servlet.GraphQLSchemaProvider.copyReadOnly(GraphQLSchemaProvider.java:11)
tomcat_1                 | 	at graphql.servlet.DefaultGraphQLSchemaProvider.<init>(DefaultGraphQLSchemaProvider.java:17)
tomcat_1                 | 	at graphql.servlet.GraphQLInvocationInputFactory.newBuilder(GraphQLInvocationInputFactory.java:91)
tomcat_1                 | 	at nl.base.servlets.GraphQLServlet.getInvocationInputFactory(GraphQLServlet.java:58)
```

**Comment by oliemansm** [comment]
Right. What I meant is that you indicate that adding this part fixes it for you:
```
.codeRegistry(schema.getCodeRegistry())
```
However, that method doesn't exist when I look at the code. If you could submit a PR with your fix I can take a look at it and merge it if it looks good.

**Comment by pvgoddijn** [comment]
Ah i found out the problem, i had the dependency to java-graphql  set to 'latest' so was using the wrong (too new) dependency for Graphql-java)

Closing because this will likely gets handled properly when updating to Graphql-java version 12.

Sorry for the overhead

**Comment by kwang1** [comment]
Hi @oliemansm , could this be re-opened? The problem still exists when using `graphql-spring-boot-starter:5.8.1` 
because GraphQL Java v12 is used.
