### ISSUE TITLE
Error in websocket session

### ISSUE THREAD

**Issue by jebbench** [graphql-java-kickstart/graphql-java-servlet#155]
When running my application and opening GraphiQL the logs are spammed with the below:

```
2019-02-28 09:33:56.325  WARN 17084 --- [pool-1-thread-6] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:56.490  WARN 17084 --- [pool-1-thread-1] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:56.606  WARN 17084 --- [pool-1-thread-3] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:56.775  WARN 17084 --- [pool-1-thread-4] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:56.870  WARN 17084 --- [pool-1-thread-8] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:56.965  WARN 17084 --- [pool-1-thread-7] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.118  WARN 17084 --- [pool-1-thread-6] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.291  WARN 17084 --- [pool-1-thread-4] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.464  WARN 17084 --- [pool-1-thread-8] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.625  WARN 17084 --- [pool-1-thread-6] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.737  WARN 17084 --- [pool-1-thread-2] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.862  WARN 17084 --- [ool-1-thread-10] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:57.976  WARN 17084 --- [pool-1-thread-5] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:58.069  WARN 17084 --- [pool-1-thread-9] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:58.211 ERROR 17084 --- [nio-8090-exec-1] graphql.servlet.GraphQLWebsocketServlet  : Error in websocket session: 4f8

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1206) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1140) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:72) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2019-02-28 09:33:58.213  WARN 17084 --- [pool-1-thread-1] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:58.305  WARN 17084 --- [pool-1-thread-2] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:58.488  WARN 17084 --- [pool-1-thread-4] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
2019-02-28 09:33:58.612  WARN 17084 --- [pool-1-thread-8] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
```

I'm not sure if it's an issue in this repository of if I've not enabled a setting somewhere? Any pointers on where to look would be appreciated.

**Comment by oliemansm** [comment]
It's an issue with this project. It assumes an Apollo subscription and the related keep alive mechanism, while GraphiQL doesn't use that.

**Comment by martijn1279** [comment]
I got the same bug

**Comment by markosfount** [comment]
If you are using graphql-spring-boot, this might help: https://www.bountysource.com/issues/70953129-graphiql-subscriptionclienttimeout-is-set-in-seconds-instead-of-ms

**Comment by MartinHein** [comment]
thank you!

It works for me

**Comment by oliemansm** [comment]
@jebbench Fixed when you upgrade `graphql-spring-boot` to version 5.7.0.
