### ISSUE TITLE
When will graphql-java-servlet update to graphql-java 12.0?

### ISSUE THREAD

**Issue by michael-fl** [graphql-java-kickstart/graphql-java-servlet#159]
graphql-java-servlet still has a dependency to graphql-java 11.0. Any plans to update to graphql-java 12.0? Support for the new @defer feature would also be cool, which was added in version 12.0.

**Comment by lburja** [comment]
Running against graphql-java 12 gives this stacktrace:
`
graphql.AssertException: Object required to be not null
	at graphql.Assert.assertNotNull(Assert.java:22) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:19) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:13) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables$Builder.build(DocumentAndVariables.java:55) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.parse(GraphQL.java:561) ~[graphql-java-12.0.jar:na]
`

Apparently 'variables' can't be null:

`
    private DocumentAndVariables(Document document, Map<String, Object> variables) {
        this.document = assertNotNull(document);
        this.variables = assertNotNull(variables);
    }
`
