### ISSUE TITLE
gradlew publishToMavenLocal --> bnd.bnd file does not exist

### ISSUE THREAD

**Issue by jeujai** [graphql-java-kickstart/graphql-java-servlet#167]
Hello,

The OSGi example doesn't seem to work. It says something about a bnd.bnd file being missing when I execute **gradlew publishToMavenLocal** 

Can you give me a hint?

Thanks,

Peter

------------------------------

Stacktrace follows

C:\osgi-serge\graphql-java-servlet-master>gradlew publishToMavenLocal --stacktrace
> Task :jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':jar'.
> File 'C:\osgi-serge\graphql-java-servlet-master\bnd.bnd' specified for property '$1' does not exist.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':jar'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:72)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.InvalidUserDataException: File 'C:\osgi-serge\graphql-java-servlet-master\bnd.bnd' specified for property '$1' does not exist.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:69)
        ... 34 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
4 actionable tasks: 2 executed, 2 up-to-date

**Comment by sergehuber** [comment]
Could you please confirm the changes you have done ? In another thread you said you had upgraded Gradle to 5.6, why aren't you using the 3.5 version provided by default in the wrapper ?

**Comment by jeujai** [comment]
Believe me Serge, I would love to use the 3.5 version provided by wrapper by default. I'm not expert enough with gradle or bndtools to be the least bit adventurous. When I try the wrapper as is, though, I get the below error. At first, I thought it was because I was using Java 11 and the project wasn't setup to do that. Then I opened gradle.properties from your pull request, saw **LIB_GRAPHQL_JAVA_VER = 11.0** and realized that 11 couldn't have been the problem because you were able to build the project using Java 11 too (can you please confirm?).

**Error:**

C:\osgi>gradlew publishToMavenLocal --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.2'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:247)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by sergehuber** [comment]
Hello Peter, 

I think there is some confusion, the LIB_GRAPHQL_JAVA_VER = 11.0 doesn't point to the version of Java but the version of the GraphQL-Java implementation (https://www.graphql-java.com/)

Actually I cannot confirm that I'm using Java 11 because I'm actually still using Java 8 because I'm working on applications that still require it.

So unfortunately this means there might be an issue with running this project on Java 11 with Gradle 5.6. Maybe you can switch to Java 8 ? Otherwise this means that a ticket for supporting Java 11 should be opened.

**Comment by jeujai** [comment]
Understood. The only issue that I may have with using Java 8 is that my current Springboot implementation uses Java 9 because the project that I originally based it on, https://github.com/graphql-java/graphql-java, seems to require it based on what I read. On the other hand, it looks like gradle 3.5.1 release date of June/2017 seems to be newer than the check-in dates of the first files in that project so I'll try Java 9 and then Java 8 if that doesn't work. In any case, since I need dynamic schema and need to ultimately convert to the https://github.com/graphql-java-kickstart project to get it working, adopting Java 8 should not be an issue.

Many thanks Serge!

Peter

**Comment by sergehuber** [comment]
I don't know where you say that GraphQL-Java requires Java 9 (which seems weird since it is not an LTS release). On the official documentation of GraphQL-Java they say it requires Java 8 or later : https://www.graphql-java.com/documentation/v12/getting-started/

Same thing on this resource: https://github.com/graphql-java-kickstart/graphql-spring-boot

So it seems like Java 8 should work. At my company we do all of our work still with Java 8 as Java 11 is still quite recent and not all frameworks have properly adapted to it yet.

**Comment by jeujai** [comment]
I started my GraphQL journey with this tutorial and revisiting it, I realized that Java 9 was required by certain versions of Springboot in combination with GraphQL: https://www.pluralsight.com/guides/building-a-graphql-server-with-spring-boot

**Comment by sergehuber** [comment]
Interesting tutorial, but if you read it closely you'll notice the author decices to use Java 9 and that it isn't required. Actually he even mentions that Spring Boot has issues with it and he replaces a JAR with another because of it.
Therefore Java 8 seems like a better option even in this case.
In general the "unstable" (non-LTS) versions should only be used for very specific work, I'd stay on LTS versions (Java 8, Java 11) for stable dev work. Java 8 is still I think the best option, although 11 is getting there fast.

I also believe the Karaf + GraphQL option is one of the most interesting one, since you can then deploy OSGi bundles that extend the schema at runtime. This is what we do in my company and it works very well.

**Comment by jeujai** [comment]
Got the OSGi example working with Java 8. It works perfectly. 

It was a while back but I remember that one of the reasons I adopted Java 9 was to take advantage of Jigsaw for dynamic schema before I knew that you and the other creators of the Java GraphQL implementation had already designed it to leverage OSGi for that purpose. Boy, am I glad you did. I only recently found out that Jigsaw can't be used in place of OSGi because of the lack of package isolation and other issues plus I had no where near deep enough knowledge about the GraphQL Servlet to make that substitution assuming that it could be done at all. 

It wasn't until I played around with one of the import statements in my Springboot code that I was made aware of the OSGi Servlet and it wasn't until I Googled the Jahia source code that I was able to confirm that it could be leveraged for dynamic schemas. You may not believe this but I had been searching on and off for this solution for many months with nearly 100% of the posters saying that dynamic schemas can't be had with GraphQL. I mean even Lee Byron said that dynamic schemas won't be (directly) supported by the spec which puzzled me cuz it is so obviously needed.

I should have (and wanted to) used Karaf + GraphQL right from the start. That's what I needed all along. 

Thank you Serge, for making this possible!

**Comment by sergehuber** [comment]
Ok I understand beter your interest in Java 9 now. I was also disappointed in Jigsaw, because I expected it to be much closer to OSGi. However our investment in OSGi predates Java 9 quite a bit and I must say (OSGi) is a very mature and very reliable technology, much more than what Jigsaw is right now. Maybe it will evolve but in the meantime I think OSGi designs are the "proper" way to do things.

Anyway, coming back to this ticket, can you close it and maybe open another one mentioning compatibility with Java 11 ?
